### ISSUE TITLE
Unable to Custom Label/Barcode setting

### ISSUE THREAD

**Issue by nastype** [drajathasan/label_mixcode_color_slims#1]
Hi, thank you for the plugin.
When I try to custom the print settings, it appears:
<img width="1388" alt="Screen Shot 2023-09-12 at 15 28 12" src="https://github.com/drajathasan/label_mixcode_color_slims/assets/53134115/68c93020-b4b3-43f3-b8c3-cd5609cfa771">
Much love!

**Comment by drajathasan** [comment]
Maybe your browser is not support Vue or path to some static file is failed.
